version: "3.7"
services:
    db:
        image: mariadb:10
        container_name: test-db
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_520_ci
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: test
        ports:
            - 3308:3306


    php:
        container_name: slim_php
        build:
            context: .
        ports:
            - '9000:9000'
        volumes:
            - ./src:/var/www/src


    webserver:
        image: xqdocker/ubuntu-nginx:latest
        container_name: test-nginx2
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/src
            - ./docker/config/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - db
    
    composer:
        image: composer:2.2.0
        command: composer dump-autoload 
        volumes:
            - ./src:/app
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - db
        ports:
            - 8888:80
        environment:
            PMA_HOST: db